export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const FETCH_CATEGORY_BEGIN = "FETCH_CATEGORY_BEGIN";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const FETCH_FOODS_BEGIN = "FETCH_FOODS_BEGIN";
export const FETCH_FOODS_SUCCESS = "FETCH_FOODS_SUCCESS";
export const FETCH_FOODS_ERROR = "FETCH_FOODS_ERROR";
export const FETCH_SINGLE_FOOD_BEGIN = "FETCH_SINGLE_FOOD_BEGIN";
export const FETCH_SINGLE_FOOD_SUCCESS = "FETCH_SINGLE_FOOD_SUCCESS";
export const FETCH_SINGLE_FOOD_ERROR = "FETCH_SINGLE_FOOD_ERROR";
export const FETCH_CATEGORY_FOODS_BEGIN = "FETCH_CATEGORY_FOODS_BEGIN";
export const FETCH_CATEGORY_FOODS_SUCCESS = "FETCH_CATEGORY_FOODS_SUCCESS";
export const FETCH_CATEGORY_FOODS_ERROR = "FETCH_CATEGORY_FOODS_ERROR";

// Programmer Name: Daniel Mikhail, BSc(Hons) Software Engineering, TP061667, APD3F2211SE
// Program Name: actions.js
// Description: to import 
// First Written on: 12 june 2023
// Edited on: 12 june 2023